name: Docker Documentation
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: false
permalink: pretty
safe: false
lsi: false
exclude: ["_scripts", "tests", "apidocs/layouts", "Gemfile", "hooks", "index.html", "404.html"]

# Component versions -- address like site.docker_ce_version
# You can't have - characters in these for non-YAML reasons

# TO USE ME:
# jekyll serve --incremental --config _config_authoring.yml

latest_engine_api_version: "1.40"
docker_ce_version: "19.03"
compose_version: "1.27.4"
compose_file_v3: "3.8"
compose_file_v2: "2.4"
machine_version: "0.16.0"
distribution_version: "2.7"

collections:
  samples:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      tree: true

  # Set the correct edit-URL for upstream resources. We usually don't create a direct
  # edit link for these, and instead point to the directory that contains the file.
  - scope:
      path: engine/api/v1.*
    values:
      edit_url: "https://github.com/docker/docker/tree/master/docs/api"
  - scope:
      path: engine/deprecated
    values:
      edit_url: "https://github.com/docker/cli/tree/master/docs/"
  - scope:
      path: engine/extend
    values:
      edit_url: "https://github.com/docker/cli/tree/master/docs/extend"
  - scope:
      path: engine/reference
    values:
      edit_url: "https://github.com/docker/cli/tree/master/docs/reference"
  - scope:
      path: engine/reference/commandline
    values:
      edit_url: "https://github.com/docker/cli/tree/master/docs/reference/commandline"
  - scope:
      path: glossary
    values:
      edit_url: "https://github.com/docker/docker.github.io/blob/master/_data/glossary.yaml"
  - scope:
      path: notary/reference
    values:
      edit_url: "https://github.com/theupdateframework/notary/tree/master/docs/reference"
  - scope:
      path: registry/configuration
    values:
      edit_url: "https://github.com/docker/distribution/tree/master/docs"
  - scope:
      path: registry/spec
    values:
      edit_url: "https://github.com/docker/distribution/tree/master/docs/spec"
  - scope:
      path: compliance
    values:
      edit_url: "https://github.com/mirantis/compliance/tree/master/docs/compliance"

  # Hide Enterprise content from sitemap, and include banner in stubs that
  # content has moved to mirantis
  - scope:
      path: "datacenter"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise moved to Mirantis
  - scope:
      path: "ee"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise moved to Mirantis

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
