[build]
publish = "public"

[context.deploy-preview.environment]
NODE_VERSION = "20"
HUGO_VERSION = "0.122.0"
HUGO_ENABLEGITINFO = "true"
HUGO_ENVIRONMENT = "preview"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

