[build]
publish = "public"

[context.deploy-preview.environment]
NODE_VERSION = "22"
NODE_ENV = "production"
HUGO_VERSION = "0.154.2"
HUGO_ENABLEGITINFO = "true"
HUGO_ENVIRONMENT = "preview"
SECRETS_SCAN_OMIT_PATHS = "public/contribute/file-conventions/index.html"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && ./hack/flatten-and-resolve.js && npx pagefind@v1.3.0"
