language: objective-c
osx_image: xcode7.2

before_install:
- xcrun simctl list
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet


script:
- set -o pipefail
- cd Support
- xcodebuild -project HockeySDK.xcodeproj -scheme "HockeySDK"
  -configuration Release -destination "platform=OS X" | xcpretty -c
