extends: conditional
message: "'%s' has no definition."
link: https://docs.docker.com/contribute/style/grammar/#acronyms-and-initialisms
level: warning
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{2,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{2,5})s?\)'
# ... with the exception of these:
exceptions:
  - ACH
  - AGPL
  - AI
  - API
  - ARM
  - ARP
  - ASP
  - AUFS
  - AWS
  - BGP     # Border Gateway Protocol
  - BIOS
  - BPF
  - BSD
  - CDI
  - CFS
  - CI
  - CIDR
  - CISA
  - CLI
  - CNCF
  - CORS
  - CPU
  - CSI
  - CSS
  - CSV
  - CUDA
  - CVE
  - DAD
  - DCT
  - DEBUG
  - DHCP
  - DMR
  - DNS
  - DOM
  - DPI
  - DSOS
  - DVP
  - ECI
  - ELK
  - FAQ
  - FPM
  - FUSE
  - GB
  - GCC
  - GDB
  - GET
  - GHSA
  - GNOME
  - GNU
  - GPG
  - GPL
  - GPU
  - GRUB
  - GTK
  - GUI
  - GUID
  - HEAD
  - HTML
  - HTTP
  - HTTPS
  - IAM
  - IBM
  - ID
  - IDE
  - IP
  - IPAM
  - IPC
  - IT
  - JAR
  - JIT
  - JSON
  - JSX
  - KDE
  - LESS
  - LLDB
  - LLM
  - LTS
  - MAC
  - MATE
  - mcp
  - MCP
  - MDM
  - MDN
  - MIME
  - MSI
  - NAT
  - NET
  - NFS
  - NOTE
  - NTFS
  - NTLM
  - NUMA
  - NVDA
  - OCI
  - OS
  - OSI
  - OSS
  - PATH
  - PDF
  - PEM
  - PHP
  - PID
  - POSIX
  - POST
  - QA
  - QEMU
  - RAM
  - REPL
  - REST
  - RFC
  - RHEL
  - RPM
  - RSA
  - SAML
  - SARIF
  - SBOM
  - SCIM
  - SCM
  - SCSS
  - SCTP
  - SDK
  - SLES
  - SLSA
  - SOCKS
  - SPDX
  - SQL
  - SSD
  - SSH
  - SSL
  - SSO
  - SVG
  - TBD
  - TCP
  - TCP
  - TIP
  - TLS
  - TODO
  - TTY
  - TXT
  - UDP
  - UI
  - URI
  - URL
  - USB
  - USD
  - UTF
  - UTS
  - UUID
  - VAT
  - VDI
  - VIP
  - VLAN
  - VM
  - VPN
  - WSL
  - XML
  - XSS
  - YAML
  - ZFS
  - ZIP
