kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-claim
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
