extends: existence
message: Use 'July 31, 2016' format, not '%s'.
link: https://deploy-preview-15350--docsdocker.netlify.app/contribute/style/grammar/#dates
ignorecase: true
level: error
nonword: true
tokens:
  - '\d{1,2} (?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) \d{4}'
