extends: capitalization
message: "Use sentence case for headings: '%s'."
level: warning
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  - Vocab/Docker/accept.txt
  - Vocab/Technology/accept.txt
  - Vocab/Industry/accept.txt
