extends: conditional
message: "'%s' has no definition."
link: https://docs.docker.com/contribute/style/grammar/#acronyms-and-initialisms
level: warning
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Za-z]+(?: |\n))+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - API
  - BIOS
  - FUSE
  - ARM
  - ASP
  - AWS
  - CLI
  - CPU
  - CSS
  - CSV
  - CVE
  - DEBUG
  - DOM
  - DPI
  - ELK
  - FAQ
  - GCC
  - GDB
  - GET
  - GHSA
  - GPU
  - GTK
  - GUI
  - HEAD
  - HTML
  - HTTP
  - HTTPS
  - IDE
  - JAR
  - JSON
  - JSX
  - LESS
  - LLDB
  - NET
  - NOTE
  - NVDA
  - OSS
  - PATH
  - PDF
  - PHP
  - POSIX
  - POST
  - RAM
  - REPL
  - RSA
  - SBOM
  - SCM
  - SCSS
  - SDK
  - SQL
  - SSH
  - SSL
  - SVG
  - TBD
  - TCP
  - TODO
  - URI
  - URL
  - USB
  - UTF
  - VAT
  - WSL
  - XML
  - XSS
  - YAML
  - ZIP
