extends: substitution
message: "Consider using '%s' instead of '%s'."
ignorecase: true
level: suggestion
swap:
  accelerate: speed up
  accentuate: stress
  accompany: go with
  accomplish: carry out|do
  accorded: given
  accordingly: so
  accrue: add
  accurate: right|exact
  acquiesce: agree
  acquire: get|buy
  addressees: you
  adjacent to: next to
  adjustment: change
  admissible: allowed
  advantageous: helpful
  advise: tell
  aggregate: total
  aircraft: plane
  alleviate: ease
  alternatives: choices|options
  ameliorate: improve
  apparent: clear|plain
  ascertain: discover|find out
  assistance: help
  attain: meet
  belated: late
  bestow: give
  cease: stop|end
  commence: begin
  compensate: pay
  comprise: form|include
  concerning: about
  confer: give|award
  consequently: so
  consolidate: merge
  constitutes: forms
  convene: meet
  demonstrate: show|prove
  depart: leave
  designate: choose
  desire: want|wish
  determine: decide|find
  detrimental: bad|harmful
  disclose: share|tell
  discontinue: stop
  disseminate: send|give
  eliminate: end
  elucidate: explain
  employ: use
  enclosed: inside|included
  encounter: meet
  endeavor: try
  enumerate: count
  equitable: fair
  equivalent: equal
  exclusively: only
  expedite: hurry
  facilitate: ease
  females: women
  finalize: complete|finish
  itemized: listed
  jeopardize: risk
  liaise: work with|partner with
  methodology: method
  necessitate: cause
  numerous: many
  objective: aim|goal
  obligate: bind|compel
  optimum: best|most
  permit: let
  portion: part
  possess: own
  procure: buy
  purchase: buy
  relocate: move
  solicit: request
  state-of-the-art: latest
  substantial: large
  sufficient: enough
  terminate: end
  transmit: send
  utilization: use
  utilize: use
