extends: substitution
message: "Consider using '%s' instead of '%s'"
link: https://docs.docker.com/contribute/style/recommended-words/
ignorecase: true
level: suggestion
action:
  name: replace
swap:
  above: previous
  adaptor: adapter
  (?:account name|accountname|user name): username
  administrate: administer
  admin: administrator
  afterwards: afterward
  allow: let
  allows: lets
  alphabetic: alphabetical
  alphanumerical: alphanumeric
  anti-aliasing: antialiasing
  anti-malware: antimalware
  anti-spyware: antispyware
  anti-virus: antivirus
  appendixes: appendices
  assembler: assembly language
  below: following
  check box: checkbox
  check boxes: checkboxes
  click: select
  deselect: clear
  disable: turn off|toggle off
  (?:drop down|dropdown): drop-down
  '\b(?:eg|e\.g\.)[\s,]': for example
  enable: turn on|toggle on
  ergo: therefore
  execute: run
  gb: GB
  gbps: Gbps
  '\b(?:ie|i\.e\.)[\s,]': that is
  kb: KB
  keypress: keystroke
  (?:log out|logout): sign out
  mb: MB
  mutices: mutexes
  paas: PaaS
  pb: PB
  repo: repository
  scroll: navigate
  (?:sign on|log on|log in|logon|login): sign in
  sign up: register
  tb: TB
  vs: versus
  wish: want
