name: build docker image when PR is opened

on: pull_request

jobs:
  build-static-page:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
      - name: print docker info
        run: docker version && docker info
      - uses: actions/checkout@v2
      - name: build image
        run: docker build --build-arg=ENABLE_ARCHIVES=false --target=current -t documentation:latest .
      - name: copy static files
        if: github.repository == 'docker/docker.github.io'
        run: docker run -v ${PWD}:/output documentation:latest cp -r /usr/share/nginx/html /output/_site
      - uses: ./.github/actions/netlify-deploy
        if: github.repository == 'docker/docker.github.io'
        with:
          directory: _site
          netlify_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_account_slug: ${{ secrets.NETLIFY_ACCOUNT_SLUG }}
          site_name: "${{ github.repository }}/${{ github.head_ref }}"
