name: remove published site from netlify

on:
  pull_request:
    types:
      - closed

jobs:
  remove-site-from-netlify:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: deploy to netlify
        uses: ./.github/actions/netlify-clean
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_NAME: ${{ github.ref }}
