name: Export Docker Tar
run-name: Exporting a tar file containing ready built docker docs ğŸš€
on: [push]
jobs:
  Generate-Tar-File:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Display Docker version
        run: docker --version
      - name: Show current release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Show dirs
        run: ls -lah
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build docker images
        run: DOCKER_BUILDKIT=1 docker build . -t dockerdocs
      - name: save image as tar file
        run: docker save -o dockerdocs.tar dockerdocs
      - name: Release the Tar Asset to Github
        uses: softprops/action-gh-release@v1
        with:
          draft: false  
          files: ${{ github.workspace }}/dockerdocs.tar
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          token: ${{ github.token }}
