name: merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# open or update publishing PR when there is a push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main-to-published:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'docker'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: published
      - name: Reset published branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          delete-branch: false
          branch: published-update
          commit-message: publish updates from main
          labels: area/release
          title: publish updates from main
          body: |
            Automated pull request for publishing docs updates.
